### ISSUE TITLE
[Trivial] : corriger le sous-titre

### ISSUE THREAD

**Issue by FrenchFlakito** [acaciasforall/acacias-harvest#7]
Transformer "Iniative"  en "initiative" !

**Comment by godiveau** [comment]
fait
![capture2](https://cloud.githubusercontent.com/assets/6840777/5817873/86ee1cd2-a0b0-11e4-8c81-6a158f742ddb.png)

**Comment by Framar94** [comment]
Apparement ça n'a pas pris la modif Gilles.

**Comment by godiveau** [comment]
pourtant tu lis bien "initiative" dans ma copie d'écran ?
ha ok je n'ai pas fait le pull request…


2015-01-20 15:40 GMT+01:00 Marché François <notifications@github.com>:

**Comment by godiveau** [comment]
le commit est là :
https://github.com/godiveau/acacias-harvest/commit/ba4a076ad59c4fa4ca32874fef2fd902f3447dfb

**Comment by Framar94** [comment]
Oui mais parce que tu es en local.
Je patauge totalement , mais c’est assez cool d’arriver à  faire des modifs en local à mon petit niveau.

**Comment by godiveau** [comment]
le commit "[image: godiveau] <https://github.com/godiveau> V3 texte FR
"initiative"
<https://github.com/godiveau/acacias-harvest/commit/ba4a076ad59c4fa4ca32874fef2fd902f3447dfb>
… <https://github.com/acaciasforall/acacias-harvest/pull/9#> "est en
attente du précédent pull request toujours pas consulté ?
https://github.com/acaciasforall/acacias-harvest/pull/9

que dois-je faire ?



Le 20 janvier 2015 16:12, Marché François <notifications@github.com> a
écrit :

> Oui mais parce que tu es en local.
> Je patauge totalement , mais c’est assez cool d’arriver à faire des modifs
> en local à mon petit niveau.
>
>
>
>
>
>
>
>

**Comment by pilou15** [comment]
fait aussi
![screenshot from 2015-01-27 18 36 32](https://cloud.githubusercontent.com/assets/9337176/5923405/8d487b06-a653-11e4-9a5b-556ee8b93efc.png)

**Comment by pilou15** [comment]
fait
![screenshot from 2015-01-28 08 48 34](https://cloud.githubusercontent.com/assets/9337176/5934099/9b41eef0-a6ca-11e4-9840-bedf0dcaa312.png)

**Comment by pilou15** [comment]
hello,qui valide ce que l'on fait , du coup me pose lma question si j'ai bien bien fait puls et tout

**Comment by godiveau** [comment]
Hello Virginie,
je ne vois pas de commits dans ta branch.



2015-01-28 15:58 GMT+01:00 pilou15 <notifications@github.com>:

**Comment by pilou15** [comment]
ba ouais c'est ce que je suis entraint de m'apercevoir , je sais pas pourquoi sa fait sa , je regarde sa :)
